# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tom Ed's Blog Site
#email: wtomed@gmail.com
description: > # this means to ignore newlines until "baseurl:" My blog site for writing and getting clarity on various things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wtomed.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wtomed

# Build settings
markdown: kramdown
